name: agu_frontend
description: "Frontend for the Afterschool Geekery_Uganda project management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  image_picker: ^1.2.3
  package_info_plus: ^10.2.1
  photo_view: ^0.15.0
  pinput: ^6.0.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_foreground: assets/icon/app_icon_foreground.png
  adaptive_icon_foreground_inset: 0
  adaptive_icon_background: "#333333"
  adaptive_icon_monochrome: assets/icon/app_icon_monochrome.png

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/nunito/OFL.txt
    - assets/fonts/montserrat/OFL.txt
    - assets/images/
    - assets/images/skill_survey/coding_1_en/
    - assets/images/skill_survey/coding_2_en/
    - assets/images/skill_survey/math_1_en/
    - assets/images/skill_survey/math_2_en/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Variable.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Variable.ttf
